### ISSUE TITLE
Server Side Rendering Error

### ISSUE THREAD

**Issue by shanieMoonlight** [nrwl/nx-examples#285]
I've set up Server Side Rendering using the procedure described here: https://nx.dev/packages/angular/generators/setup-ssr.
Everything seems to be set up properly and the code compiles but as soon as I open the app in the browser I get the below error.

Compiled successfully.
** Angular Universal Live Development Server is listening on http://localhost:4200, open your browser on http://localhost:4200 **
Angular is running in development mode.

TypeError: document.documentElement.setAttribute is not a function
    at createDocument (./node_modules/@nguniversal/common/node_modules/critters/dist/critters.mjs:517:30)
    at <anonymous> (./node_modules/@nguniversal/common/node_modules/critters/dist/critters.mjs:1119:22)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:1)
    at _next (./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:22:1)
    at executor (./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:27:1)
    at ZoneAwarePromise (./node_modules/zone.js/dist/zone-node.js:1268:25)
    at <anonymous> (./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:19:1)
    at process (./node_modules/@nguniversal/common/node_modules/critters/dist/critters.mjs:1143:19)
    at <anonymous> (./node_modules/@nguniversal/common/fesm2022/tools.mjs:138:40)
Angular is running in development mode.

This happens with all my applications.
I have generated new applications (using generate -> application ) and added nothing else to make sure it wasn't my code causing the error, but the error still occurs.

To make sure it's an NX issue I created a new app outside of NX just using the angular-cli and then added SSR.
I used the procedure described here: https://angular.io/guide/universal .
I run it using ng run angular-tour-of-heroes:serve-ssr and everything works.
When I open "View Source" I can see all the prerendered elements.

Is there a way around this?

**Comment by shanieMoonlight** [comment]
I think this is in the wrong section.
