### ISSUE TITLE
Workspace creation error

### ISSUE THREAD

**Issue by sajidali2444** [nrwl/nx-examples#44]
Hi,
Following error occurred during workspace creation.
can you give me direction what am doing wrong?

Sajids-MacBook-Pro:~ Sajid$ create-nx-workspace demo-workspace
Creating a sandbox with the CLI and Nx Schematics...
[fsevents] Success: "/private/var/folders/hp/2ghd8_6n48d8mm1hcg_2hp4w0000gn/T/tmp-5443WXGVxrJaXwPz/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote
added 425 packages in 14.795s
ng new "demo-workspace" --collection=@nrwl/schematics
Could not find module "@ngrx/schematics" from "/Users/Sajid".
Error: Could not find module "@ngrx/schematics" from "/Users/Sajid".
    at Object.resolve (/Users/Sajid/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at NodeModulesEngineHost._resolvePackageJson (/Users/Sajid/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:29:21)
    at NodeModulesEngineHost._resolveCollectionPath (/Users/Sajid/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:70:40)
    at NodeModulesEngineHost.createCollectionDescription (/Users/Sajid/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:106:27)
    at SchematicEngine._createCollectionDescription (/Users/Sajid/node_modules/@angular-devkit/schematics/src/engine/engine.js:78:40)
    at SchematicEngine._createCollectionDescription (/Users/Sajid/node_modules/@angular-devkit/schematics/src/engine/engine.js:89:48)
    at SchematicEngine.createCollection (/Users/Sajid/node_modules/@angular-devkit/schematics/src/engine/engine.js:71:43)
    at Object.getCollection (/Users/Sajid/node_modules/@angular/cli/utilities/schematics.js:28:31)
    at NewCommand.getOptions (/Users/Sajid/node_modules/@angular/cli/models/schematic-command.js:194:41)
    at NewCommand.initialize (/Users/Sajid/node_modules/@angular/cli/commands/new.js:48:21)
child_process.js:615
    throw err;
    ^

Error: Command failed: /var/folders/hp/2ghd8_6n48d8mm1hcg_2hp4w0000gn/T/tmp-5443WXGVxrJaXwPz/node_modules/.bin/ng new "demo-workspace" --skip-install --collection=@nrwl/schematics
    at checkExecSyncError (child_process.js:575:11)
    at Object.execSync (child_process.js:612:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/@nrwl/schematics/bin/create-nx-workspace.js:83:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
Sajids-MacBook-Pro:~ Sajid$

**Comment by Yonet** [comment]
@sajidali2444 due to a cli issue, you have to do one extra step:
```
sudo npm i @nrwl/schematics -g
sudo npm i @ngrx/schematics -g
ng new workspace --collection @nrwl/schematics
```

Thank you for reporting. I will update the doc.
